#!/bin/sh
set -efu

pys=$(pyversions -r)

dest=$ADTTMP
for f in $(find IPython -name tests -type d); do
  mkdir -p $dest/$(dirname $f)
  cp -a $f $dest/$(dirname $f)
done
mkdir -p $dest/IPython/scripts/
cp IPython/scripts/iptest $dest/IPython/scripts/
cd $dest

#disabled, just fills disk with junk even before its used by ipython
#service mongodb start 2>&1 || true
for py in $pys; do
  for pkg in ipython ipython-notebook ipython-qtconsole; do
    for f in $(dpkg -L $pkg | grep /usr/lib/$py/dist-packages); do
      lf=$(echo $f | sed -e "s#/usr/lib/$py/dist-packages/##")
      [ -d $f ] && mkdir -p $lf
    done
    for f in $(dpkg -L $pkg | grep /usr/lib/$py/dist-package); do
      lf=$(echo $f | sed -e "s#/usr/lib/$py/dist-packages/##")
      [ -f $f ] && [ ! -e $lf ] && ln -s $f $lf
    done
  done
  LC_ALL=C.UTF-8 HOME=$PWD \
  PATH=$PWD/IPython/scripts/:$PATH PYTHONPATH=$PWD \
  xvfb-run -a -s "-screen 0 1280x1024x24 -noreset" \
  $py $PWD/IPython/scripts/iptest -v -e test_not_writable_ipdir; \
done

#service mongodb stop 2>&1 || true
