#!/bin/sh
set -efu

pys=$(py3versions -r)

dest=$ADTTMP
for f in $(find IPython -name tests -type d); do
  mkdir -p $dest/$(dirname $f)
  cp -a $f $dest/$(dirname $f)
done
cd $dest

export TMPDIR=$ADTTMP

#disabled, just fills disk with junk even before its used by ipython
#service mongodb start 2>&1 || true
  for pkg in ipython3 ipython3-notebook ipython3-qtconsole; do
    for f in $(dpkg -L $pkg | grep /usr/lib/python3/dist-packages); do
      lf=$(echo $f | sed -e "s#/usr/lib/python3/dist-packages/##")
      [ -d $f ] && mkdir -p $lf
    done
    for f in $(dpkg -L $pkg | grep /usr/lib/python3/dist-package); do
      lf=$(echo $f | sed -e "s#/usr/lib/python3/dist-packages/##")
      [ -f $f ] && [ ! -e $lf ] && ln -s $f $lf
    done
  done

for py in $pys; do
  export PYTHONPATH=$PWD
  mkdir -p test-$py
  cd test-$py
  LC_ALL=C.UTF-8 HOME=$PWD \
  xvfb-run -a -s "-screen 0 1280x1024x24 -noreset" \
  $py -c "from IPython.testing.iptestcontroller import main; main()" -- -v -e test_not_writable_ipdir -e test_console_starts -e test_exit_code_signal;
  cd -
done

#service mongodb stop 2>&1 || true
